allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@1.85.0'
  - '@oxlint/binding-android-arm64@1.85.0'
  - '@oxlint/binding-darwin-arm64@1.85.0'
  - '@oxlint/binding-darwin-x64@1.85.0'
  - '@oxlint/binding-freebsd-x64@1.85.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.85.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.85.0'
  - '@oxlint/binding-linux-arm64-gnu@1.85.0'
  - '@oxlint/binding-linux-arm64-musl@1.85.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.85.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.85.0'
  - '@oxlint/binding-linux-riscv64-musl@1.85.0'
  - '@oxlint/binding-linux-s390x-gnu@1.85.0'
  - '@oxlint/binding-linux-x64-gnu@1.85.0'
  - '@oxlint/binding-linux-x64-musl@1.85.0'
  - '@oxlint/binding-openharmony-arm64@1.85.0'
  - '@oxlint/binding-win32-arm64-msvc@1.85.0'
  - '@oxlint/binding-win32-ia32-msvc@1.85.0'
  - '@oxlint/binding-win32-x64-msvc@1.85.0'
  - oxlint@1.85.0
overrides:
  postcss: ^8.5.10
  vite: ^7.3.5
  esbuild: ^0.28.1
  shell-quote: ^1.8.4
  serialize-javascript: ^7.0.5
  picomatch@2.3.1: ^2.3.2
  picomatch@4.0.3: ^4.0.4
  minimatch@3.1.2: ^3.1.3
