# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on: 
  push:
    branches-ignore:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run build
    - run: npm test
      env:
        CI: true
        NODE_ENV: development
        AFPNEWS_BASE_URL: ${{ secrets.AFPNEWS_BASE_URL }}
        AFPNEWS_API_KEY: ${{ secrets.AFPNEWS_API_KEY }}
        AFPNEWS_CLIENT_ID: ${{ secrets.AFPNEWS_CLIENT_ID }}
        AFPNEWS_CLIENT_SECRET: ${{ secrets.AFPNEWS_CLIENT_SECRET }}
        AFPNEWS_USERNAME: ${{ secrets.AFPNEWS_USERNAME }}
        AFPNEWS_PASSWORD: ${{ secrets.AFPNEWS_PASSWORD }}
        AFPNEWS_CUSTOM_AUTH_URL: ${{ secrets.AFPNEWS_CUSTOM_AUTH_URL }}
